### ISSUE TITLE
Add url of the repo in the source code List tile

### ISSUE THREAD

**Issue by Spyy004** [Spyy004/LifeList#11]
In the settings page, the 'source code' list tile doesn't have any functionality. We need to redirect the user to Lifelist's GitHub repo on the tap of that item.

**Comment by JatinSharma32** [comment]
If this method is not good enough then, 
I have another method to achieve this task in my mind

**Comment by JatinSharma32** [comment]
Exams going on, tight schedule 😅
Made a new PR check it please

**Comment by Spyy004** [comment]
You missed adding permissions in the manifest file. Make sure you check these things as well from next time.
