### ISSUE TITLE
App throwing exception despite field having correct character count

### ISSUE THREAD

**Issue by subramanian42** [Spyy004/LifeList#15]
I recently encountered an issue while using the app, where even though I entered the required number of characters in the input field, the app keeps throwing an exception. This problem is preventing me from using the app effectively, and I would like to resolve it. Therefore, I have created a Github issue to bring this matter to the attention of the developers. 

PS: The exception does not contain the string "first name".

<img src="https://user-images.githubusercontent.com/88108372/232768381-db84f301-31f3-427c-8bb6-725bb0503a90.jpg"  width="200" height="400">

**Comment by Spyy004** [comment]
Good observation. Please go ahead and fix the issue. Make sure you have read the Contributing.md file properly. I am assigning you this task

**Comment by Spyy004** [comment]
any updates @subramanian42 ?
