### ISSUE TITLE
Done button fixed position in Add Task modal

### ISSUE THREAD

**Issue by Spyy004** [Spyy004/LifeList#22]
The done button should not scroll down with the list. It should stay at the bottom

https://user-images.githubusercontent.com/54628130/233147740-8a012a14-b1e8-48ee-80cd-82a5dc675836.mp4

**Comment by bahadirtrkalioglu** [comment]
Hello I fixed this issue so I will make a pull request:)

**Comment by Spyy004** [comment]
I made some comments on the PR. please have a look

**Comment by Spyy004** [comment]
Thanks for a good PR. :)

**Comment by bahadirtrkalioglu** [comment]
No problem, I want to work on this project :)

**Comment by Spyy004** [comment]
In that case, you can find more such places in the app where you can see the button go down with the list and fix the position of the button. It would be very helpful

**Comment by bahadirtrkalioglu** [comment]
Okey, I can do that. Could you say which page has this problem? I didn't see It.
Btw, I can add Turkish language support to app

**Comment by Spyy004** [comment]
That would be awesome. We need support for as many languages as possible. Just add a new arb file with all the translations and run the `flutter gen-l10n` command

**Comment by Spyy004** [comment]
> Okey, I can do that. Could you say which page has this problem? I didn't see It. Btw, I can add Turkish language support to app

In the create bucket screen, the create button would scroll down with the scroll view. Currently, the view fits in the single page so it works fine but in the future when we will provide more options while creating a bucket, the done button will go down as well. You can fix that if you wish to
