### ISSUE TITLE
While changing the bucket the title is still persisted

### ISSUE THREAD

**Issue by arxxv** [Spyy004/LifeList#31]
If I open a bucket, go back and open a different bucket, the bucket name displayed is that of the former bucket

**Comment by arxxv** [comment]
Also the category of the previous bucket is persisted

**Comment by arxxv** [comment]
https://user-images.githubusercontent.com/51039549/233479053-fca64fa9-ccfc-42a6-a523-594cf2283222.mp4

**Comment by Spyy004** [comment]
fixed in the latest release
