### ISSUE TITLE
Deletion of all the tasks

### ISSUE THREAD

**Issue by arxxv** [Spyy004/LifeList#33]
Upon deletion of all tasks, either the bucket should be allowed to exits without any tasks or there should be a prompt confirming that this will delete the task. 
For me the former suggestion makes more sense, and a user should be allowed to have a bucket without any tasks

**Comment by Spyy004** [comment]
prompt for task deletion is present in the latest release. A bucket must have at least one task...

**Comment by arxxv** [comment]
Let's say I want to use your app as a grocery list app. I shouldn't be forced to create a grocery list bucket every single time. Instead I should be able to keep the bucket and change the tasks within. 
I might have not understood the purpose of the app properly, if that's the case, then go ahead and close the issue!

**Comment by Spyy004** [comment]
Valid point. This makes a bucket more generic.  it might be best to allow for empty buckets, as some users might want to create a bucket for a future goal they have not yet defined any tasks for.

However, to encourage users to actively work towards completing tasks and achieving goals, you may want to make it mandatory for buckets to have at least one task to help users get started and stay motivated. 

The second point resonates more with the app's idea so we will go ahead with the current design. If more demand comes for deletion of all tasks, then we will divert to that approach.
