### ISSUE TITLE
Render issue in Feedback Screen

### ISSUE THREAD

**Issue by Spyy004** [Spyy004/LifeList#52]
![Screenshot_2023-04-27-20-53-20-34_0f6aa42c4176743a0eb3af48518c4b1c.jpg](https://user-images.githubusercontent.com/54628130/234909928-0dba3f75-82ff-494b-b8d6-e6755044de73.jpg)

**Comment by aliu691** [comment]
hi, have you fixed this yet?
if no I can help fix it

**Comment by Spyy004** [comment]
This is not fixed yet. Please go ahead and do it.

**Comment by aliu691** [comment]
alright

**Comment by aliu691** [comment]
PR raised

**Comment by Spyy004** [comment]
Merged. Don't forget to star the repo :)
