### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by Ujjwalsharma2210** [Spyy004/LifeList#54]
Hi, I liked this project and want to start contributing but facing this issue. Can anyone help me solve this?
Android version: 11 RKQ1.200826.002
Flutter version: 3.7.12
Dart version: 2.19.6

ERROR: 
```
Target of URI doesn't exist: 'package:flutter_gen/gen_l10n/app_localizations.dart'.
Try creating the file referenced by the URI, or try using a URI for a file that does exist.
package:flutter_gen/gen_l10n/app_localizations.dart
```

**Comment by Spyy004** [comment]
It is unable to find the app_localizations,dart file
Run these commands if you are running the project for the first time
flutter clean
flutter pub get
flutter gen-l10n
flutter build --debug

You are probably missing the third command i guess. I must update the Readme

**Comment by Ujjwalsharma2210** [comment]
Thanks, @Spyy004 
It's working now.
